version: "3.8"
networks:
  intern-app:
    driver: bridge
services:
  api:
    container_name: api
    build: .
    ports:
      - ${PORT}:${PORT}
    restart: always
    environment:
      - PORT=${PORT}
    networks:
      - intern-app
    depends_on:
      - db
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
  db:
    container_name: db
    image: postgres:15-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - intern-app
  db-tests:
    container_name: dbtests
    image: postgres:15-alpine
    ports:
      - ${POSTGRES_TESTS_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - intern-app
volumes:
  pgdata: